<a href="https://colab.research.google.com/github/aish0606/DeepLearning/blob/main/Pytorch%20Practice/loss_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Loss Function https://pytorch.org/docs/stable/nn.html#loss-functions
import torch
import torch.nn as nn

In [2]:
prediction = torch.randn(4, 5)
print(prediction)
label = torch.randn(4, 5)
print(label)

tensor([[-1.2529e+00,  3.0899e-04,  1.9775e-01, -8.7060e-03,  1.5012e+00],
        [-3.3792e+00,  1.2335e+00, -7.1523e-01, -1.1711e-04, -5.3109e-01],
        [-5.4657e-01, -5.1835e-01,  2.4756e-01, -6.8553e-01,  2.1664e+00],
        [ 9.0522e-01, -1.2532e+00,  1.3977e+00,  1.5329e+00,  1.7440e+00]])
tensor([[-0.4065,  1.0029, -0.3129, -1.0072,  0.2646],
        [-0.8414,  1.2894, -2.4591,  0.5987,  1.5337],
        [ 0.4710,  0.6282, -1.2357,  0.0735,  1.0880],
        [ 1.1560, -1.5619, -0.0673, -1.7178, -1.5669]])


**MSE Loss**

In [3]:
mse = nn.MSELoss(reduction='mean')
loss = mse(prediction, label)
print(loss)

tensor(2.4369)


In [4]:
# Python Code for MSE Loss
py_loss = ((prediction - label) ** 2).mean()
print(py_loss)

tensor(2.4369)


**Binary Cross Entrpy Loss** - In BCE the label would be values with either 0 or 1. 
The predicted values should be between 0 and 1. Therefore we pass the o/p in sigmoid activation fn

In [5]:
# We need to redefine the label as 0 or 1
label = torch.zeros(4,5).random_(0,2) # In place random function with lower & upper limit not included
print(label)

tensor([[1., 1., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 1., 0., 1., 0.],
        [0., 0., 1., 0., 0.]])


In [6]:
# Sigmoid fn
sigmoid = nn.Sigmoid()

In [7]:
bce = nn.BCELoss(reduction='mean')
bce_loss = bce(sigmoid(prediction), label)
print(bce_loss)

tensor(0.9281)


In [8]:
# BCEWithLogitsLoss: This loss combines a Sigmoid layer and the BCELoss in one single class.
bces = nn.BCEWithLogitsLoss(reduction='mean')
bces_loss = bces(prediction, label)
print(bces_loss)

tensor(0.9281)


In [9]:
import numpy as np

# Implementing BCE in Python or Python Code
# converting torch tensor to numpy array
prediction_py = prediction.numpy()
label_py = label.numpy()

print(label_py)
print(len(label_py))
print(label_py[0])
print(len(label_py[0]))

[[1. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
4
[1. 1. 1. 0. 0.]
5


In [10]:
def sigmoid(val):
  return 1 / (1 + np.exp(-val))


In [11]:
# prediction_py should have value b/w 0 and 1
prediction_py = sigmoid(prediction_py)
loss_val = []
for i in range(len(label_py)):
  batch_loss = []
  for j in range(len(label_py)):
    batch_loss.append(-np.log(prediction_py[i][j]) if label_py[i][j] == 1 else -np.log(1 - prediction_py[i][j]))
  loss_val.append(batch_loss)

print(np.mean(loss_val))

0.7636165684552303
