<a href="https://colab.research.google.com/github/aish0606/DeepLearning/blob/main/Pytorch%20Practice/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torchvision

In [ ]:
torch.cuda.is_available()

True

In [ ]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


In [ ]:
# this is 1D tensor
a = torch.tensor([2,2,1])
print(a)
# .shape is an Attribute
print(a.shape)
# .size() is a method, The out for both are same
print(a.size())

tensor([2, 2, 1])
torch.Size([3])
torch.Size([3])


In [ ]:
b = torch.tensor([[4,3,1],[2,6,7],[9,7,0],[11,55,99]])
print(b)
print(b.shape)
print(b.size())

tensor([[ 4,  3,  1],
        [ 2,  6,  7],
        [ 9,  7,  0],
        [11, 55, 99]])
torch.Size([4, 3])
torch.Size([4, 3])


In [ ]:
# Mean can be calculated for just Float and Double datatypes.
c = torch.DoubleTensor([2,2,2])
print(c.mean())

tensor(2., dtype=torch.float64)


In [ ]:
d = torch.FloatTensor([[4,3,1],[2,6,7],[9,7,0],[11,55,99]])
print(d)
print(d.shape)
print(d.size())
print(d.dtype)
print(d.mean())
print(d.std())

tensor([[ 4.,  3.,  1.],
        [ 2.,  6.,  7.],
        [ 9.,  7.,  0.],
        [11., 55., 99.]])
torch.Size([4, 3])
torch.Size([4, 3])
torch.float32
tensor(17.)
tensor(29.7321)


In [ ]:
# Reshaping the tensor b. For reshaping we use .view functipn Pytorch
print(b.view(-1,1))
print(b.view(-1,4))
print(b.view(3,-1))
print(b.view(6,-1))

tensor([[ 4],
        [ 3],
        [ 1],
        [ 2],
        [ 6],
        [ 7],
        [ 9],
        [ 7],
        [ 0],
        [11],
        [55],
        [99]])
tensor([[ 4,  3,  1,  2],
        [ 6,  7,  9,  7],
        [ 0, 11, 55, 99]])
tensor([[ 4,  3,  1,  2],
        [ 6,  7,  9,  7],
        [ 0, 11, 55, 99]])
tensor([[ 4,  3],
        [ 1,  2],
        [ 6,  7],
        [ 9,  7],
        [ 0, 11],
        [55, 99]])


In [ ]:
# Create a matrix of random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.2655, 0.6313, 0.1569, 0.9017],
        [0.0836, 0.0881, 0.1787, 0.6528],
        [0.5023, 0.5603, 0.2458, 0.6442],
        [0.8263, 0.3210, 0.5312, 0.4502]])


In [3]:
# Create a matrix of random numbers taken from normal distribution with mean 0 and variance 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-0.4187,  0.2077,  1.0328,  0.1040],
        [ 1.7606,  1.0788,  1.6095, -0.1841],
        [ 1.8335,  0.4154,  0.5622, -0.1601],
        [ 0.6777,  1.1372,  0.0116,  1.6291]])
torch.float32


In [ ]:
# Create a 1D array of 5 random integers from 6 to 9
in_arr = torch.randint(6,9,(5,))
print(in_arr)
# Create a 2D array of 5 random integers from 6 to 9
in_arr2 = torch.randint(6,10,(3,3))
print(in_arr2)

tensor([6, 7, 8, 8, 6])
tensor([[9, 8, 9],
        [6, 7, 7],
        [8, 8, 9]])


In [ ]:
# Get the number of element in in_arr and in_arr2
print(torch.numel(in_arr))
print(torch.numel(in_arr2))

5
9


In [5]:
# Construct a 3x3 matrix of zeros and of dtype long
z = torch.zeros(3,3, dtype=torch.long)
print(z)
print(z.dtype)
y = torch.ones(3,3)
print(y)
print(y.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [4]:
# randn_like take the size of the matrix from r2
r2_like = torch.randn_like(r2, dtype=torch.double)
print(r2)

tensor([[-0.4187,  0.2077,  1.0328,  0.1040],
        [ 1.7606,  1.0788,  1.6095, -0.1841],
        [ 1.8335,  0.4154,  0.5622, -0.1601],
        [ 0.6777,  1.1372,  0.0116,  1.6291]])


In [7]:
# Adding 2 tensor: we need to make sure the size of the 2 tensors are same and data type should be same
add_res = torch.add(r2, r2_like)
print(add_res)

tensor([[-1.2303, -0.9866,  1.6997, -0.6679],
        [ 3.8708,  2.1951,  1.0973,  0.5370],
        [ 2.6538, -0.3584,  1.3180, -1.0746],
        [-0.1155,  1.6521, -1.9146,  1.4257]], dtype=torch.float64)


In [9]:
# In place Addition, r2 is updated with result value
r2.add_(r2_like)
print(r2)

tensor([[-2.0418, -2.1808,  2.3666, -1.4398],
        [ 5.9810,  3.3113,  0.5852,  1.2581],
        [ 3.4742, -1.1323,  2.0738, -1.9891],
        [-0.9088,  2.1671, -3.8408,  1.2222]])


**Numpy Bridge** - Converting a numpy array to tensor and vice-versa

In [10]:
import numpy as np

In [13]:
# Converting a torch tensor to numpy array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
# the change in a is reflected in b also
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
# Converting a Numpy array to torch tensor
# Here changing the numpy array changed the tensor automatically
a = np.ones(3)
print(a.dtype)
b = torch.from_numpy(a)
print(b.dtype)
np.add(a,1,out=a)
print(a)
print(b)

float64
torch.float64
[2. 2. 2.]
tensor([2., 2., 2.], dtype=torch.float64)


In [17]:
# Move the tensor to GPU
print(r2)
r2 = r2.cuda()
print(r2)

tensor([[-2.0418, -2.1808,  2.3666, -1.4398],
        [ 5.9810,  3.3113,  0.5852,  1.2581],
        [ 3.4742, -1.1323,  2.0738, -1.9891],
        [-0.9088,  2.1671, -3.8408,  1.2222]])
tensor([[-2.0418, -2.1808,  2.3666, -1.4398],
        [ 5.9810,  3.3113,  0.5852,  1.2581],
        [ 3.4742, -1.1323,  2.0738, -1.9891],
        [-0.9088,  2.1671, -3.8408,  1.2222]], device='cuda:0')


In [18]:
# Easy switching between CPU and GPU
cuda = torch.cuda.is_available()
print(cuda)
if cuda:
  add_res = add_res.cuda()
  print(add_res)

True
tensor([[-1.2303, -0.9866,  1.6997, -0.6679],
        [ 3.8708,  2.1951,  1.0973,  0.5370],
        [ 2.6538, -0.3584,  1.3180, -1.0746],
        [-0.1155,  1.6521, -1.9146,  1.4257]], device='cuda:0',
       dtype=torch.float64)


In [20]:
# We can convert a list to tensor
lst = [6,7,8]
print(lst)
lst = torch.tensor(lst)
print(lst, lst.dtype)

[6, 7, 8]
tensor([6, 7, 8]) torch.int64


In [21]:
data = [[2. ,3.], [5. ,9.],
        [2. ,3.], [5. ,9.]]
print(data, type(data))        
T = torch.tensor(data)
print(T, T.dtype)


[[2.0, 3.0], [5.0, 9.0], [2.0, 3.0], [5.0, 9.0]] <class 'list'>
tensor([[2., 3.],
        [5., 9.],
        [2., 3.],
        [5., 9.]]) torch.float32


**Tensor Concatenation**

In [24]:
tensor1 = torch.randn(2, 3)
print(tensor1)
tensor2 = torch.randn(5, 3)
print(tensor2)
# concatenate along 0 dimension or CONCATENATE ROWS
con_1 = torch.cat([tensor1, tensor2])
print(con_1)
print('\n\n')
tensor1 = torch.randn(3, 2)
print(tensor1)
tensor2 = torch.randn(3, 5)
print(tensor2)
# concatenate along 1 dimension or CONCATENATE COLUMNS
con_1 = torch.cat([tensor1, tensor2], dim=1)
print(con_1)


tensor([[ 0.2967, -0.6749, -1.3157],
        [-0.6103,  0.7025,  2.6447]])
tensor([[ 0.0038, -3.3342, -0.9580],
        [ 1.4554,  1.5511, -0.7022],
        [ 0.4924,  0.6124,  1.8163],
        [ 0.0057, -0.8522,  0.5536],
        [-0.1817, -1.2256,  1.0948]])
tensor([[ 0.2967, -0.6749, -1.3157],
        [-0.6103,  0.7025,  2.6447],
        [ 0.0038, -3.3342, -0.9580],
        [ 1.4554,  1.5511, -0.7022],
        [ 0.4924,  0.6124,  1.8163],
        [ 0.0057, -0.8522,  0.5536],
        [-0.1817, -1.2256,  1.0948]])



tensor([[-0.8165, -0.9521],
        [ 0.5293,  1.0212],
        [ 1.2403,  1.3038]])
tensor([[-0.1655,  1.1650, -0.0833,  0.6291, -0.8394],
        [ 0.0656,  0.0179, -1.6986, -1.1353, -0.0925],
        [ 0.2201,  0.0811,  1.1025, -0.9253,  0.1634]])
tensor([[-0.8165, -0.9521, -0.1655,  1.1650, -0.0833,  0.6291, -0.8394],
        [ 0.5293,  1.0212,  0.0656,  0.0179, -1.6986, -1.1353, -0.0925],
        [ 1.2403,  1.3038,  0.2201,  0.0811,  1.1025, -0.9253,  0.1634]])


**Adding Dimensions to TENSORS**

In [38]:
tensor_1 = torch.tensor([1, 4, 7, 8])
print(tensor_1, tensor_1.dtype, tensor_1.shape)

tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a, tensor_a.dtype, tensor_a.shape)

tensor_b = torch.unsqueeze(tensor_1, dim=1)
print(tensor_b, tensor_b.dtype, tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2,3,4) # 2 channels, 3 rows, 4 columns
print(tensor_2, tensor_2.dtype, tensor_2.shape)
tensor_c = torch.unsqueeze(tensor_2, dim=2)
# shape of Tensor changed from [2,3,4] to [2,3,1,4] as we have added the new dimension at 2 (dim=2)
print(tensor_c, tensor_c.dtype, tensor_c.shape)


tensor([1, 4, 7, 8]) torch.int64 torch.Size([4])
tensor([[1, 4, 7, 8]]) torch.int64 torch.Size([1, 4])
tensor([[1],
        [4],
        [7],
        [8]]) torch.int64 torch.Size([4, 1])


tensor([[[0.0031, 0.2112, 0.0928, 0.8901],
         [0.7873, 0.5909, 0.2507, 0.0355],
         [0.8979, 0.0516, 0.7825, 0.9855]],

        [[0.2502, 0.5370, 0.0396, 0.6458],
         [0.0433, 0.5032, 0.9098, 0.7848],
         [0.0221, 0.4397, 0.7798, 0.9651]]]) torch.float32 torch.Size([2, 3, 4])
tensor([[[[0.0031, 0.2112, 0.0928, 0.8901]],

         [[0.7873, 0.5909, 0.2507, 0.0355]],

         [[0.8979, 0.0516, 0.7825, 0.9855]]],


        [[[0.2502, 0.5370, 0.0396, 0.6458]],

         [[0.0433, 0.5032, 0.9098, 0.7848]],

         [[0.0221, 0.4397, 0.7798, 0.9651]]]]) torch.float32 torch.Size([2, 3, 1, 4])


**Auto Grad (or Automatic Differentiation)**

In [7]:
# If requires_grad=True, Tensor object keeps the track how it was created
x = torch.tensor([2.,3.,4.], requires_grad=True)
y = torch.tensor([99., 4., 8.], requires_grad=True)
# Since reuires_grad=True for both x and y, therefore we can compute gradient w.r.t. them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
# z is showing as <AddBackward0 object at 0x7f2d8e245b00>, AddBackward as z=x+y (x, y are added)
# Going Further
s = z.sum()
print(s)
# s is showing as <SumBackward0 object at 0x7f2d8e245da0>, SumBackward as s=z.sum() (elements of z are summed up)
print(s.grad_fn)

tensor([101.,   7.,  12.], grad_fn=<AddBackward0>)
tensor(120., grad_fn=<SumBackward0>)


In [10]:
# Now if we backpropogate on s, we can find the gradient of s w.r.t. x
s.backward()
print(x.grad)

tensor([2., 2., 2.])


In [22]:
# By default, tensors have requires_grad=False
x = torch.randn(2,2)
y = torch.randn(2,2)
print(x.requires_grad,y.requires_grad)
z = x + y
# Can't backprop through z
print(z.grad_fn)
# Another way to set the requires_grad = True (in place) is
x.requires_grad_()
y.requires_grad_()
z = x + y
print(z.grad_fn)
print(z.requires_grad)
# Gives o/p as TRUE bcoz Now z has the computation history that relates itself to x and y

print("--------DETACHED z--------")
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history
new_z = z.detach()
print(new_z.grad_fn)

print("-------To Stop Autograd ---------")
# You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
  # there is no grad for the derived value of x
  print((x+10).requires_grad)
  print(x.requires_grad)

False False
None
True
--------DETACHED z--------
None
-------To Stop Autograd ---------
True
True
False
True


In [29]:


#One More example
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)

# x.grad is gradient of out w.r.t. x
out.backward()
print(x.grad)



tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
