<a href="https://colab.research.google.com/github/aish0606/DeepLearning/blob/main/%20Pytorch%20Practice/weight_init.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# https://pytorch.org/docs/stable/nn.init.html
import torch
import torch.nn as nn

In [2]:
layer = nn.Linear(5,5)

In [7]:
print(layer.weight)
print(layer.bias.data)
print(layer.bias)

Parameter containing:
tensor([[-0.2741, -0.3766, -0.4199, -0.2985, -0.2755],
        [-0.1797, -0.1591, -0.1124,  0.0914,  0.2848],
        [-0.4178,  0.3090, -0.3469, -0.2833, -0.4449],
        [-0.4123,  0.0624, -0.1436,  0.0566,  0.3768],
        [-0.2879,  0.2137,  0.1262,  0.3538, -0.1861]], requires_grad=True)
tensor([-0.3678, -0.3453, -0.4265,  0.1834,  0.1935])
Parameter containing:
tensor([-0.3678, -0.3453, -0.4265,  0.1834,  0.1935], requires_grad=True)


In [11]:
nn.init.uniform_(layer.weight, a=0.0,b=5) # in uniform_ '_' means inplace operation

Parameter containing:
tensor([[1.2795, 1.5414, 0.2297, 1.3370, 3.1425],
        [3.8304, 4.4316, 2.6413, 1.0802, 0.2888],
        [0.8049, 0.6679, 4.9105, 1.4672, 0.1670],
        [2.8772, 0.5100, 1.5791, 2.7369, 3.2951],
        [0.4679, 0.2703, 1.3017, 0.7821, 1.1442]], requires_grad=True)

In [14]:
nn.init.normal_(layer.weight, mean=0, std=5.0)

Parameter containing:
tensor([[ 5.9892, -2.0039, -3.0401, -7.5103,  1.4927],
        [-1.6669, -0.5521,  6.2566,  5.4991,  5.3312],
        [-4.1349, -1.6218,  2.7428,  1.7911, -4.6667],
        [-7.5998,  1.4721,  9.2318,  3.6768, -5.1760],
        [ 3.7911,  3.2966,  2.7498,  1.3364, -2.7034]], requires_grad=True)

In [17]:
# Constant initialization:- Weight should not initiazed as constant. Bias can initialized as CONSTANTS
nn.init.constant_(layer.bias, 7)

Parameter containing:
tensor([7., 7., 7., 7., 7.], requires_grad=True)

In [20]:
nn.init.zeros_(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [18]:
layer.bias

Parameter containing:
tensor([7., 7., 7., 7., 7.], requires_grad=True)

In [21]:
nn.init.xavier_uniform_(layer.weight, gain=1.0)

Parameter containing:
tensor([[-0.1610,  0.0655, -0.3522,  0.0449,  0.6796],
        [-0.2245, -0.2333,  0.6017,  0.2497, -0.5601],
        [ 0.3243,  0.4957, -0.0229,  0.0090, -0.0558],
        [ 0.3399,  0.2963,  0.2018,  0.6669, -0.1425],
        [ 0.2864,  0.4834,  0.3756, -0.2500,  0.2948]], requires_grad=True)

In [25]:
nn.init.xavier_normal_(layer.weight, gain=1.0)

Parameter containing:
tensor([[-0.0537,  0.4353,  0.3600, -0.3226,  0.1663],
        [-0.6984, -0.4196, -0.4488,  0.0378, -0.3572],
        [-0.5433,  0.0549,  0.1123,  0.5232,  0.1993],
        [-0.2711, -0.4655, -0.0218,  0.1957, -0.0876],
        [-0.2740, -0.1295, -0.1070,  0.1347, -0.0680]], requires_grad=True)